// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: billing.proto

package subscriptionbillingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriptionBillingApi_CreateProduct_FullMethodName                = "/subscriptionbilling.SubscriptionBillingApi/CreateProduct"
	SubscriptionBillingApi_CreatePlan_FullMethodName                   = "/subscriptionbilling.SubscriptionBillingApi/CreatePlan"
	SubscriptionBillingApi_CreatePrice_FullMethodName                  = "/subscriptionbilling.SubscriptionBillingApi/CreatePrice"
	SubscriptionBillingApi_CreateOffer_FullMethodName                  = "/subscriptionbilling.SubscriptionBillingApi/CreateOffer"
	SubscriptionBillingApi_EnableOffer_FullMethodName                  = "/subscriptionbilling.SubscriptionBillingApi/EnableOffer"
	SubscriptionBillingApi_DisableOffer_FullMethodName                 = "/subscriptionbilling.SubscriptionBillingApi/DisableOffer"
	SubscriptionBillingApi_AttachEntitlementToPlan_FullMethodName      = "/subscriptionbilling.SubscriptionBillingApi/AttachEntitlementToPlan"
	SubscriptionBillingApi_ConfigureTrialPolicy_FullMethodName         = "/subscriptionbilling.SubscriptionBillingApi/ConfigureTrialPolicy"
	SubscriptionBillingApi_ConfigureBillingPolicy_FullMethodName       = "/subscriptionbilling.SubscriptionBillingApi/ConfigureBillingPolicy"
	SubscriptionBillingApi_ListPlans_FullMethodName                    = "/subscriptionbilling.SubscriptionBillingApi/ListPlans"
	SubscriptionBillingApi_UpdatePlan_FullMethodName                   = "/subscriptionbilling.SubscriptionBillingApi/UpdatePlan"
	SubscriptionBillingApi_PublishPlan_FullMethodName                  = "/subscriptionbilling.SubscriptionBillingApi/PublishPlan"
	SubscriptionBillingApi_ArchivePlan_FullMethodName                  = "/subscriptionbilling.SubscriptionBillingApi/ArchivePlan"
	SubscriptionBillingApi_StartTrial_FullMethodName                   = "/subscriptionbilling.SubscriptionBillingApi/StartTrial"
	SubscriptionBillingApi_StartSubscription_FullMethodName            = "/subscriptionbilling.SubscriptionBillingApi/StartSubscription"
	SubscriptionBillingApi_CancelSubscription_FullMethodName           = "/subscriptionbilling.SubscriptionBillingApi/CancelSubscription"
	SubscriptionBillingApi_ChangePlan_FullMethodName                   = "/subscriptionbilling.SubscriptionBillingApi/ChangePlan"
	SubscriptionBillingApi_GetSubscriptionStatus_FullMethodName        = "/subscriptionbilling.SubscriptionBillingApi/GetSubscriptionStatus"
	SubscriptionBillingApi_GetCurrentSubscription_FullMethodName       = "/subscriptionbilling.SubscriptionBillingApi/GetCurrentSubscription"
	SubscriptionBillingApi_CheckEntitlement_FullMethodName             = "/subscriptionbilling.SubscriptionBillingApi/CheckEntitlement"
	SubscriptionBillingApi_GetEntitlementSnapshot_FullMethodName       = "/subscriptionbilling.SubscriptionBillingApi/GetEntitlementSnapshot"
	SubscriptionBillingApi_RefreshEntitlementSnapshot_FullMethodName   = "/subscriptionbilling.SubscriptionBillingApi/RefreshEntitlementSnapshot"
	SubscriptionBillingApi_RecordUsage_FullMethodName                  = "/subscriptionbilling.SubscriptionBillingApi/RecordUsage"
	SubscriptionBillingApi_CreateInvoice_FullMethodName                = "/subscriptionbilling.SubscriptionBillingApi/CreateInvoice"
	SubscriptionBillingApi_GetInvoice_FullMethodName                   = "/subscriptionbilling.SubscriptionBillingApi/GetInvoice"
	SubscriptionBillingApi_ListInvoices_FullMethodName                 = "/subscriptionbilling.SubscriptionBillingApi/ListInvoices"
	SubscriptionBillingApi_MarkManualInvoicePaid_FullMethodName        = "/subscriptionbilling.SubscriptionBillingApi/MarkManualInvoicePaid"
	SubscriptionBillingApi_RetryPayment_FullMethodName                 = "/subscriptionbilling.SubscriptionBillingApi/RetryPayment"
	SubscriptionBillingApi_RefundPayment_FullMethodName                = "/subscriptionbilling.SubscriptionBillingApi/RefundPayment"
	SubscriptionBillingApi_CreatePaymentIntent_FullMethodName          = "/subscriptionbilling.SubscriptionBillingApi/CreatePaymentIntent"
	SubscriptionBillingApi_ConfirmPayment_FullMethodName               = "/subscriptionbilling.SubscriptionBillingApi/ConfirmPayment"
	SubscriptionBillingApi_GetPaymentStatus_FullMethodName             = "/subscriptionbilling.SubscriptionBillingApi/GetPaymentStatus"
	SubscriptionBillingApi_ExtendSubscription_FullMethodName           = "/subscriptionbilling.SubscriptionBillingApi/ExtendSubscription"
	SubscriptionBillingApi_RestrictSubscription_FullMethodName         = "/subscriptionbilling.SubscriptionBillingApi/RestrictSubscription"
	SubscriptionBillingApi_ExpireSubscription_FullMethodName           = "/subscriptionbilling.SubscriptionBillingApi/ExpireSubscription"
	SubscriptionBillingApi_GrantCustomEntitlement_FullMethodName       = "/subscriptionbilling.SubscriptionBillingApi/GrantCustomEntitlement"
	SubscriptionBillingApi_ViewLedgerTransactions_FullMethodName       = "/subscriptionbilling.SubscriptionBillingApi/ViewLedgerTransactions"
	SubscriptionBillingApi_ViewAuditOutboxEvents_FullMethodName        = "/subscriptionbilling.SubscriptionBillingApi/ViewAuditOutboxEvents"
	SubscriptionBillingApi_ReplayAuditOutboxEvent_FullMethodName       = "/subscriptionbilling.SubscriptionBillingApi/ReplayAuditOutboxEvent"
	SubscriptionBillingApi_ReplayDomainEventOutboxEvent_FullMethodName = "/subscriptionbilling.SubscriptionBillingApi/ReplayDomainEventOutboxEvent"
	SubscriptionBillingApi_ReceivePaystackWebhook_FullMethodName       = "/subscriptionbilling.SubscriptionBillingApi/ReceivePaystackWebhook"
)

// SubscriptionBillingApiClient is the client API for SubscriptionBillingApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionBillingApiClient interface {
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	CreatePrice(ctx context.Context, in *CreatePriceRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	CreateOffer(ctx context.Context, in *CreateOfferRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	EnableOffer(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	DisableOffer(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	AttachEntitlementToPlan(ctx context.Context, in *AttachEntitlementToPlanRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	ConfigureTrialPolicy(ctx context.Context, in *ConfigureTrialPolicyRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	ConfigureBillingPolicy(ctx context.Context, in *ConfigureBillingPolicyRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	ListPlans(ctx context.Context, in *ListPlansRequest, opts ...grpc.CallOption) (*ListPlansResponse, error)
	UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	PublishPlan(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	ArchivePlan(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*PlanResponse, error)
	StartTrial(ctx context.Context, in *StartTrialRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	StartSubscription(ctx context.Context, in *StartSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	CancelSubscription(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	ChangePlan(ctx context.Context, in *ChangePlanRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	GetSubscriptionStatus(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*SubscriptionStatusResponse, error)
	GetCurrentSubscription(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	CheckEntitlement(ctx context.Context, in *CheckEntitlementRequest, opts ...grpc.CallOption) (*CheckEntitlementResponse, error)
	GetEntitlementSnapshot(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*EntitlementSnapshotResponse, error)
	RefreshEntitlementSnapshot(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*EntitlementSnapshotResponse, error)
	RecordUsage(ctx context.Context, in *RecordUsageRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	CreateInvoice(ctx context.Context, in *CreateInvoiceRequest, opts ...grpc.CallOption) (*InvoiceResponse, error)
	GetInvoice(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*InvoiceResponse, error)
	ListInvoices(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*ListInvoicesResponse, error)
	MarkManualInvoicePaid(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*InvoiceResponse, error)
	RetryPayment(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	RefundPayment(ctx context.Context, in *RefundPaymentRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	CreatePaymentIntent(ctx context.Context, in *CreatePaymentIntentRequest, opts ...grpc.CallOption) (*PaymentIntentResponse, error)
	ConfirmPayment(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	GetPaymentStatus(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*PaymentResponse, error)
	ExtendSubscription(ctx context.Context, in *ExtendSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	RestrictSubscription(ctx context.Context, in *ReasonedEntityRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	ExpireSubscription(ctx context.Context, in *ReasonedEntityRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error)
	GrantCustomEntitlement(ctx context.Context, in *GrantCustomEntitlementRequest, opts ...grpc.CallOption) (*EntityResponse, error)
	ViewLedgerTransactions(ctx context.Context, in *OptionalSubscriptionRequest, opts ...grpc.CallOption) (*ViewLedgerTransactionsResponse, error)
	ViewAuditOutboxEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ViewAuditOutboxEventsResponse, error)
	ReplayAuditOutboxEvent(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ReplayDomainEventOutboxEvent(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ReceivePaystackWebhook(ctx context.Context, in *ReceivePaystackWebhookRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type subscriptionBillingApiClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionBillingApiClient(cc grpc.ClientConnInterface) SubscriptionBillingApiClient {
	return &subscriptionBillingApiClient{cc}
}

func (c *subscriptionBillingApiClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) CreatePlan(ctx context.Context, in *CreatePlanRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_CreatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) CreatePrice(ctx context.Context, in *CreatePriceRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_CreatePrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) CreateOffer(ctx context.Context, in *CreateOfferRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_CreateOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) EnableOffer(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_EnableOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) DisableOffer(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_DisableOffer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) AttachEntitlementToPlan(ctx context.Context, in *AttachEntitlementToPlanRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_AttachEntitlementToPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ConfigureTrialPolicy(ctx context.Context, in *ConfigureTrialPolicyRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ConfigureTrialPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ConfigureBillingPolicy(ctx context.Context, in *ConfigureBillingPolicyRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ConfigureBillingPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ListPlans(ctx context.Context, in *ListPlansRequest, opts ...grpc.CallOption) (*ListPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlansResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ListPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) UpdatePlan(ctx context.Context, in *UpdatePlanRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_UpdatePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) PublishPlan(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_PublishPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ArchivePlan(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*PlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ArchivePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) StartTrial(ctx context.Context, in *StartTrialRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_StartTrial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) StartSubscription(ctx context.Context, in *StartSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_StartSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) CancelSubscription(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_CancelSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ChangePlan(ctx context.Context, in *ChangePlanRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ChangePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) GetSubscriptionStatus(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*SubscriptionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionStatusResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_GetSubscriptionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) GetCurrentSubscription(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_GetCurrentSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) CheckEntitlement(ctx context.Context, in *CheckEntitlementRequest, opts ...grpc.CallOption) (*CheckEntitlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckEntitlementResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_CheckEntitlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) GetEntitlementSnapshot(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*EntitlementSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntitlementSnapshotResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_GetEntitlementSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) RefreshEntitlementSnapshot(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*EntitlementSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntitlementSnapshotResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_RefreshEntitlementSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) RecordUsage(ctx context.Context, in *RecordUsageRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_RecordUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) CreateInvoice(ctx context.Context, in *CreateInvoiceRequest, opts ...grpc.CallOption) (*InvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvoiceResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_CreateInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) GetInvoice(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*InvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvoiceResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_GetInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ListInvoices(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*ListInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvoicesResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ListInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) MarkManualInvoicePaid(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*InvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvoiceResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_MarkManualInvoicePaid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) RetryPayment(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_RetryPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) RefundPayment(ctx context.Context, in *RefundPaymentRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_RefundPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) CreatePaymentIntent(ctx context.Context, in *CreatePaymentIntentRequest, opts ...grpc.CallOption) (*PaymentIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentIntentResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_CreatePaymentIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ConfirmPayment(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ConfirmPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) GetPaymentStatus(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*PaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_GetPaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ExtendSubscription(ctx context.Context, in *ExtendSubscriptionRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ExtendSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) RestrictSubscription(ctx context.Context, in *ReasonedEntityRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_RestrictSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ExpireSubscription(ctx context.Context, in *ReasonedEntityRequest, opts ...grpc.CallOption) (*SubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscriptionResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ExpireSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) GrantCustomEntitlement(ctx context.Context, in *GrantCustomEntitlementRequest, opts ...grpc.CallOption) (*EntityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_GrantCustomEntitlement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ViewLedgerTransactions(ctx context.Context, in *OptionalSubscriptionRequest, opts ...grpc.CallOption) (*ViewLedgerTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewLedgerTransactionsResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ViewLedgerTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ViewAuditOutboxEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ViewAuditOutboxEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewAuditOutboxEventsResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ViewAuditOutboxEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ReplayAuditOutboxEvent(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ReplayAuditOutboxEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ReplayDomainEventOutboxEvent(ctx context.Context, in *EntityIdRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ReplayDomainEventOutboxEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriptionBillingApiClient) ReceivePaystackWebhook(ctx context.Context, in *ReceivePaystackWebhookRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, SubscriptionBillingApi_ReceivePaystackWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionBillingApiServer is the server API for SubscriptionBillingApi service.
// All implementations must embed UnimplementedSubscriptionBillingApiServer
// for forward compatibility.
type SubscriptionBillingApiServer interface {
	CreateProduct(context.Context, *CreateProductRequest) (*EntityResponse, error)
	CreatePlan(context.Context, *CreatePlanRequest) (*EntityResponse, error)
	CreatePrice(context.Context, *CreatePriceRequest) (*EntityResponse, error)
	CreateOffer(context.Context, *CreateOfferRequest) (*EntityResponse, error)
	EnableOffer(context.Context, *EntityIdRequest) (*EntityResponse, error)
	DisableOffer(context.Context, *EntityIdRequest) (*EntityResponse, error)
	AttachEntitlementToPlan(context.Context, *AttachEntitlementToPlanRequest) (*EntityResponse, error)
	ConfigureTrialPolicy(context.Context, *ConfigureTrialPolicyRequest) (*EntityResponse, error)
	ConfigureBillingPolicy(context.Context, *ConfigureBillingPolicyRequest) (*EntityResponse, error)
	ListPlans(context.Context, *ListPlansRequest) (*ListPlansResponse, error)
	UpdatePlan(context.Context, *UpdatePlanRequest) (*PlanResponse, error)
	PublishPlan(context.Context, *EntityIdRequest) (*PlanResponse, error)
	ArchivePlan(context.Context, *EntityIdRequest) (*PlanResponse, error)
	StartTrial(context.Context, *StartTrialRequest) (*SubscriptionResponse, error)
	StartSubscription(context.Context, *StartSubscriptionRequest) (*SubscriptionResponse, error)
	CancelSubscription(context.Context, *EntityIdRequest) (*SubscriptionResponse, error)
	ChangePlan(context.Context, *ChangePlanRequest) (*SubscriptionResponse, error)
	GetSubscriptionStatus(context.Context, *EntityIdRequest) (*SubscriptionStatusResponse, error)
	GetCurrentSubscription(context.Context, *CustomerRequest) (*SubscriptionResponse, error)
	CheckEntitlement(context.Context, *CheckEntitlementRequest) (*CheckEntitlementResponse, error)
	GetEntitlementSnapshot(context.Context, *EntityIdRequest) (*EntitlementSnapshotResponse, error)
	RefreshEntitlementSnapshot(context.Context, *EntityIdRequest) (*EntitlementSnapshotResponse, error)
	RecordUsage(context.Context, *RecordUsageRequest) (*EntityResponse, error)
	CreateInvoice(context.Context, *CreateInvoiceRequest) (*InvoiceResponse, error)
	GetInvoice(context.Context, *EntityIdRequest) (*InvoiceResponse, error)
	ListInvoices(context.Context, *CustomerRequest) (*ListInvoicesResponse, error)
	MarkManualInvoicePaid(context.Context, *EntityIdRequest) (*InvoiceResponse, error)
	RetryPayment(context.Context, *EntityIdRequest) (*PaymentResponse, error)
	RefundPayment(context.Context, *RefundPaymentRequest) (*EntityResponse, error)
	CreatePaymentIntent(context.Context, *CreatePaymentIntentRequest) (*PaymentIntentResponse, error)
	ConfirmPayment(context.Context, *EntityIdRequest) (*PaymentResponse, error)
	GetPaymentStatus(context.Context, *EntityIdRequest) (*PaymentResponse, error)
	ExtendSubscription(context.Context, *ExtendSubscriptionRequest) (*SubscriptionResponse, error)
	RestrictSubscription(context.Context, *ReasonedEntityRequest) (*SubscriptionResponse, error)
	ExpireSubscription(context.Context, *ReasonedEntityRequest) (*SubscriptionResponse, error)
	GrantCustomEntitlement(context.Context, *GrantCustomEntitlementRequest) (*EntityResponse, error)
	ViewLedgerTransactions(context.Context, *OptionalSubscriptionRequest) (*ViewLedgerTransactionsResponse, error)
	ViewAuditOutboxEvents(context.Context, *Empty) (*ViewAuditOutboxEventsResponse, error)
	ReplayAuditOutboxEvent(context.Context, *EntityIdRequest) (*StatusResponse, error)
	ReplayDomainEventOutboxEvent(context.Context, *EntityIdRequest) (*StatusResponse, error)
	ReceivePaystackWebhook(context.Context, *ReceivePaystackWebhookRequest) (*StatusResponse, error)
	mustEmbedUnimplementedSubscriptionBillingApiServer()
}

// UnimplementedSubscriptionBillingApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriptionBillingApiServer struct{}

func (UnimplementedSubscriptionBillingApiServer) CreateProduct(context.Context, *CreateProductRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) CreatePlan(context.Context, *CreatePlanRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlan not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) CreatePrice(context.Context, *CreatePriceRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePrice not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) CreateOffer(context.Context, *CreateOfferRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOffer not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) EnableOffer(context.Context, *EntityIdRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableOffer not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) DisableOffer(context.Context, *EntityIdRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableOffer not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) AttachEntitlementToPlan(context.Context, *AttachEntitlementToPlanRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachEntitlementToPlan not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ConfigureTrialPolicy(context.Context, *ConfigureTrialPolicyRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureTrialPolicy not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ConfigureBillingPolicy(context.Context, *ConfigureBillingPolicyRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureBillingPolicy not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ListPlans(context.Context, *ListPlansRequest) (*ListPlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlans not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) UpdatePlan(context.Context, *UpdatePlanRequest) (*PlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePlan not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) PublishPlan(context.Context, *EntityIdRequest) (*PlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishPlan not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ArchivePlan(context.Context, *EntityIdRequest) (*PlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchivePlan not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) StartTrial(context.Context, *StartTrialRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTrial not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) StartSubscription(context.Context, *StartSubscriptionRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSubscription not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) CancelSubscription(context.Context, *EntityIdRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelSubscription not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ChangePlan(context.Context, *ChangePlanRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePlan not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) GetSubscriptionStatus(context.Context, *EntityIdRequest) (*SubscriptionStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscriptionStatus not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) GetCurrentSubscription(context.Context, *CustomerRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentSubscription not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) CheckEntitlement(context.Context, *CheckEntitlementRequest) (*CheckEntitlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckEntitlement not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) GetEntitlementSnapshot(context.Context, *EntityIdRequest) (*EntitlementSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntitlementSnapshot not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) RefreshEntitlementSnapshot(context.Context, *EntityIdRequest) (*EntitlementSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshEntitlementSnapshot not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) RecordUsage(context.Context, *RecordUsageRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordUsage not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) CreateInvoice(context.Context, *CreateInvoiceRequest) (*InvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInvoice not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) GetInvoice(context.Context, *EntityIdRequest) (*InvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInvoice not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ListInvoices(context.Context, *CustomerRequest) (*ListInvoicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvoices not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) MarkManualInvoicePaid(context.Context, *EntityIdRequest) (*InvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkManualInvoicePaid not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) RetryPayment(context.Context, *EntityIdRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryPayment not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) RefundPayment(context.Context, *RefundPaymentRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundPayment not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) CreatePaymentIntent(context.Context, *CreatePaymentIntentRequest) (*PaymentIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePaymentIntent not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ConfirmPayment(context.Context, *EntityIdRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPayment not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) GetPaymentStatus(context.Context, *EntityIdRequest) (*PaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentStatus not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ExtendSubscription(context.Context, *ExtendSubscriptionRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendSubscription not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) RestrictSubscription(context.Context, *ReasonedEntityRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestrictSubscription not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ExpireSubscription(context.Context, *ReasonedEntityRequest) (*SubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExpireSubscription not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) GrantCustomEntitlement(context.Context, *GrantCustomEntitlementRequest) (*EntityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantCustomEntitlement not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ViewLedgerTransactions(context.Context, *OptionalSubscriptionRequest) (*ViewLedgerTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ViewLedgerTransactions not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ViewAuditOutboxEvents(context.Context, *Empty) (*ViewAuditOutboxEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ViewAuditOutboxEvents not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ReplayAuditOutboxEvent(context.Context, *EntityIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayAuditOutboxEvent not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ReplayDomainEventOutboxEvent(context.Context, *EntityIdRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayDomainEventOutboxEvent not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) ReceivePaystackWebhook(context.Context, *ReceivePaystackWebhookRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceivePaystackWebhook not implemented")
}
func (UnimplementedSubscriptionBillingApiServer) mustEmbedUnimplementedSubscriptionBillingApiServer() {
}
func (UnimplementedSubscriptionBillingApiServer) testEmbeddedByValue() {}

// UnsafeSubscriptionBillingApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionBillingApiServer will
// result in compilation errors.
type UnsafeSubscriptionBillingApiServer interface {
	mustEmbedUnimplementedSubscriptionBillingApiServer()
}

func RegisterSubscriptionBillingApiServer(s grpc.ServiceRegistrar, srv SubscriptionBillingApiServer) {
	// If the following call panics, it indicates UnimplementedSubscriptionBillingApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriptionBillingApi_ServiceDesc, srv)
}

func _SubscriptionBillingApi_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_CreatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).CreatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_CreatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).CreatePlan(ctx, req.(*CreatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_CreatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).CreatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_CreatePrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).CreatePrice(ctx, req.(*CreatePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_CreateOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).CreateOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_CreateOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).CreateOffer(ctx, req.(*CreateOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_EnableOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).EnableOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_EnableOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).EnableOffer(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_DisableOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).DisableOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_DisableOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).DisableOffer(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_AttachEntitlementToPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachEntitlementToPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).AttachEntitlementToPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_AttachEntitlementToPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).AttachEntitlementToPlan(ctx, req.(*AttachEntitlementToPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ConfigureTrialPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureTrialPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ConfigureTrialPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ConfigureTrialPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ConfigureTrialPolicy(ctx, req.(*ConfigureTrialPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ConfigureBillingPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureBillingPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ConfigureBillingPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ConfigureBillingPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ConfigureBillingPolicy(ctx, req.(*ConfigureBillingPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ListPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ListPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ListPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ListPlans(ctx, req.(*ListPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_UpdatePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).UpdatePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_UpdatePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).UpdatePlan(ctx, req.(*UpdatePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_PublishPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).PublishPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_PublishPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).PublishPlan(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ArchivePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ArchivePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ArchivePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ArchivePlan(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_StartTrial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTrialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).StartTrial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_StartTrial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).StartTrial(ctx, req.(*StartTrialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_StartSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).StartSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_StartSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).StartSubscription(ctx, req.(*StartSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_CancelSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).CancelSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_CancelSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).CancelSubscription(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ChangePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ChangePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ChangePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ChangePlan(ctx, req.(*ChangePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_GetSubscriptionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).GetSubscriptionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_GetSubscriptionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).GetSubscriptionStatus(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_GetCurrentSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).GetCurrentSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_GetCurrentSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).GetCurrentSubscription(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_CheckEntitlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEntitlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).CheckEntitlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_CheckEntitlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).CheckEntitlement(ctx, req.(*CheckEntitlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_GetEntitlementSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).GetEntitlementSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_GetEntitlementSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).GetEntitlementSnapshot(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_RefreshEntitlementSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).RefreshEntitlementSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_RefreshEntitlementSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).RefreshEntitlementSnapshot(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_RecordUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).RecordUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_RecordUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).RecordUsage(ctx, req.(*RecordUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_CreateInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).CreateInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_CreateInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).CreateInvoice(ctx, req.(*CreateInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_GetInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).GetInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_GetInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).GetInvoice(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ListInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ListInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ListInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ListInvoices(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_MarkManualInvoicePaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).MarkManualInvoicePaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_MarkManualInvoicePaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).MarkManualInvoicePaid(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_RetryPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).RetryPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_RetryPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).RetryPayment(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_RefundPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).RefundPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_RefundPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).RefundPayment(ctx, req.(*RefundPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_CreatePaymentIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).CreatePaymentIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_CreatePaymentIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).CreatePaymentIntent(ctx, req.(*CreatePaymentIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ConfirmPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ConfirmPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ConfirmPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ConfirmPayment(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_GetPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).GetPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_GetPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).GetPaymentStatus(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ExtendSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ExtendSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ExtendSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ExtendSubscription(ctx, req.(*ExtendSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_RestrictSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReasonedEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).RestrictSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_RestrictSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).RestrictSubscription(ctx, req.(*ReasonedEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ExpireSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReasonedEntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ExpireSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ExpireSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ExpireSubscription(ctx, req.(*ReasonedEntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_GrantCustomEntitlement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantCustomEntitlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).GrantCustomEntitlement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_GrantCustomEntitlement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).GrantCustomEntitlement(ctx, req.(*GrantCustomEntitlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ViewLedgerTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionalSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ViewLedgerTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ViewLedgerTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ViewLedgerTransactions(ctx, req.(*OptionalSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ViewAuditOutboxEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ViewAuditOutboxEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ViewAuditOutboxEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ViewAuditOutboxEvents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ReplayAuditOutboxEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ReplayAuditOutboxEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ReplayAuditOutboxEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ReplayAuditOutboxEvent(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ReplayDomainEventOutboxEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ReplayDomainEventOutboxEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ReplayDomainEventOutboxEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ReplayDomainEventOutboxEvent(ctx, req.(*EntityIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriptionBillingApi_ReceivePaystackWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceivePaystackWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBillingApiServer).ReceivePaystackWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriptionBillingApi_ReceivePaystackWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBillingApiServer).ReceivePaystackWebhook(ctx, req.(*ReceivePaystackWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriptionBillingApi_ServiceDesc is the grpc.ServiceDesc for SubscriptionBillingApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionBillingApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscriptionbilling.SubscriptionBillingApi",
	HandlerType: (*SubscriptionBillingApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _SubscriptionBillingApi_CreateProduct_Handler,
		},
		{
			MethodName: "CreatePlan",
			Handler:    _SubscriptionBillingApi_CreatePlan_Handler,
		},
		{
			MethodName: "CreatePrice",
			Handler:    _SubscriptionBillingApi_CreatePrice_Handler,
		},
		{
			MethodName: "CreateOffer",
			Handler:    _SubscriptionBillingApi_CreateOffer_Handler,
		},
		{
			MethodName: "EnableOffer",
			Handler:    _SubscriptionBillingApi_EnableOffer_Handler,
		},
		{
			MethodName: "DisableOffer",
			Handler:    _SubscriptionBillingApi_DisableOffer_Handler,
		},
		{
			MethodName: "AttachEntitlementToPlan",
			Handler:    _SubscriptionBillingApi_AttachEntitlementToPlan_Handler,
		},
		{
			MethodName: "ConfigureTrialPolicy",
			Handler:    _SubscriptionBillingApi_ConfigureTrialPolicy_Handler,
		},
		{
			MethodName: "ConfigureBillingPolicy",
			Handler:    _SubscriptionBillingApi_ConfigureBillingPolicy_Handler,
		},
		{
			MethodName: "ListPlans",
			Handler:    _SubscriptionBillingApi_ListPlans_Handler,
		},
		{
			MethodName: "UpdatePlan",
			Handler:    _SubscriptionBillingApi_UpdatePlan_Handler,
		},
		{
			MethodName: "PublishPlan",
			Handler:    _SubscriptionBillingApi_PublishPlan_Handler,
		},
		{
			MethodName: "ArchivePlan",
			Handler:    _SubscriptionBillingApi_ArchivePlan_Handler,
		},
		{
			MethodName: "StartTrial",
			Handler:    _SubscriptionBillingApi_StartTrial_Handler,
		},
		{
			MethodName: "StartSubscription",
			Handler:    _SubscriptionBillingApi_StartSubscription_Handler,
		},
		{
			MethodName: "CancelSubscription",
			Handler:    _SubscriptionBillingApi_CancelSubscription_Handler,
		},
		{
			MethodName: "ChangePlan",
			Handler:    _SubscriptionBillingApi_ChangePlan_Handler,
		},
		{
			MethodName: "GetSubscriptionStatus",
			Handler:    _SubscriptionBillingApi_GetSubscriptionStatus_Handler,
		},
		{
			MethodName: "GetCurrentSubscription",
			Handler:    _SubscriptionBillingApi_GetCurrentSubscription_Handler,
		},
		{
			MethodName: "CheckEntitlement",
			Handler:    _SubscriptionBillingApi_CheckEntitlement_Handler,
		},
		{
			MethodName: "GetEntitlementSnapshot",
			Handler:    _SubscriptionBillingApi_GetEntitlementSnapshot_Handler,
		},
		{
			MethodName: "RefreshEntitlementSnapshot",
			Handler:    _SubscriptionBillingApi_RefreshEntitlementSnapshot_Handler,
		},
		{
			MethodName: "RecordUsage",
			Handler:    _SubscriptionBillingApi_RecordUsage_Handler,
		},
		{
			MethodName: "CreateInvoice",
			Handler:    _SubscriptionBillingApi_CreateInvoice_Handler,
		},
		{
			MethodName: "GetInvoice",
			Handler:    _SubscriptionBillingApi_GetInvoice_Handler,
		},
		{
			MethodName: "ListInvoices",
			Handler:    _SubscriptionBillingApi_ListInvoices_Handler,
		},
		{
			MethodName: "MarkManualInvoicePaid",
			Handler:    _SubscriptionBillingApi_MarkManualInvoicePaid_Handler,
		},
		{
			MethodName: "RetryPayment",
			Handler:    _SubscriptionBillingApi_RetryPayment_Handler,
		},
		{
			MethodName: "RefundPayment",
			Handler:    _SubscriptionBillingApi_RefundPayment_Handler,
		},
		{
			MethodName: "CreatePaymentIntent",
			Handler:    _SubscriptionBillingApi_CreatePaymentIntent_Handler,
		},
		{
			MethodName: "ConfirmPayment",
			Handler:    _SubscriptionBillingApi_ConfirmPayment_Handler,
		},
		{
			MethodName: "GetPaymentStatus",
			Handler:    _SubscriptionBillingApi_GetPaymentStatus_Handler,
		},
		{
			MethodName: "ExtendSubscription",
			Handler:    _SubscriptionBillingApi_ExtendSubscription_Handler,
		},
		{
			MethodName: "RestrictSubscription",
			Handler:    _SubscriptionBillingApi_RestrictSubscription_Handler,
		},
		{
			MethodName: "ExpireSubscription",
			Handler:    _SubscriptionBillingApi_ExpireSubscription_Handler,
		},
		{
			MethodName: "GrantCustomEntitlement",
			Handler:    _SubscriptionBillingApi_GrantCustomEntitlement_Handler,
		},
		{
			MethodName: "ViewLedgerTransactions",
			Handler:    _SubscriptionBillingApi_ViewLedgerTransactions_Handler,
		},
		{
			MethodName: "ViewAuditOutboxEvents",
			Handler:    _SubscriptionBillingApi_ViewAuditOutboxEvents_Handler,
		},
		{
			MethodName: "ReplayAuditOutboxEvent",
			Handler:    _SubscriptionBillingApi_ReplayAuditOutboxEvent_Handler,
		},
		{
			MethodName: "ReplayDomainEventOutboxEvent",
			Handler:    _SubscriptionBillingApi_ReplayDomainEventOutboxEvent_Handler,
		},
		{
			MethodName: "ReceivePaystackWebhook",
			Handler:    _SubscriptionBillingApi_ReceivePaystackWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing.proto",
}
